version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'



  backend:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
